openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3333
  - url: https://agenda.tibagi.pr.gov.br
paths:
  /:
    get:
      responses:
        '200':
          description: OK

  /events:
    get:
      responses:
        '200':
          description: Retorna lista de eventos.
        '400':
          description: Retorna mensagem de erro.
