openapi: '3.0.2'
info:
  title: API Agentur
  version: '1.0'

# 1) Define the security scheme type (HTTP bearer)
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
    Auth:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    SucessLogin:
      type: object
      properties:
        type:
          type: string
        token:
          type: string
          format: token
    Events:
      type: object
      properties:
        title:
          type: string
        info:
          type: string
        place:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

servers:
  - url: http://localhost:3333
  - url: https://agenda.tibagi.pr.gov.br
paths:
  /events:
    get:
      tags:
        - "events"
      responses:
        '200':
          description: Retorna lista de eventos.
        '400':
          description: Retorna mensagem de erro.
    post:
      tags:
        - "events"
      security:
        - bearerAuth: []
      requestBody:
        description: Objeto de tipo evento
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Events"
      responses:
        '200':
          description: Adiciona um evento
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Events"
  /events/{id}:
    delete:
      tags:
        - events
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Id do evento que deseja deletar
      responses:
        '200':
          description: Deletado com sucesso

  /users:
    post:
      tags:
        - "users"
      security:
        - bearerAuth: []
      requestBody:
        description: Dados do usuário
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: Adicionado um usuário
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /users/auth:
    post:
      tags:
        - "users"
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Auth"
      responses:
        '200':
          description: Autentica o usuário
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SucessLogin"



